CC=CC

OUTPUTBIN= udf-example
OUTPUTSRC= udf-example.cpp 

CFLAGS=  -std=c++11  -I.  -L.  -O3  -flto 
#-I/project/projectdirs/m1248/hdf5/hdf5-1.8.14-suren-patch/build/include  
CCFLAGS= -std=c++11  -I.  -L.  -O3  -flto 
#-I/project/projectdirs/m1248/hdf5/hdf5-1.8.14-suren-patch/build/include
#LIBS= -lhdf5 -lhdf5_hl -lz -L/project/projectdirs/m1248/hdf5/hdf5-1.8.14-suren-patch/build/lib
#-lmpi 



.PHONY:all
all:$(OUTPUTBIN)
$(OUTPUTBIN): $(OUTPUTSRC) fake-HDF5-data.c udf-bx.cpp udf-s3d.cpp udf-openmsi.cpp udf-neon.cpp
	$(CC) fake-HDF5-data.c -o fake-HDF5-data  $(CFLAGS) $(CCFLAGS) $(LIBS)
	$(CC) udf-bx.cpp      -o udf-bx      $(CFLAGS) $(CCFLAGS) $(LIBS)
	$(CC) udf-s1.cpp      -o udf-s1      $(CFLAGS) $(CCFLAGS) $(LIBS) 
	$(CC) udf-openmsi.cpp -o udf-openmsi $(CFLAGS) $(CCFLAGS) $(LIBS)
	$(CC) udf-s3d.cpp     -o udf-s3d     $(CFLAGS) $(CCFLAGS) $(LIBS)
	$(CC) udf-neon.cpp    -o udf-neon    $(CFLAGS) $(CCFLAGS) $(LIBS)
	$(CC) udf-s2.cpp      -o udf-s2      $(CFLAGS) $(CCFLAGS) $(LIBS) 
	

.PHONY:clean
clean:
	rm  -rf $(OUTPUTBIN) fake-HDF5-data udf-bx udf-s3d udf-openmsi udf-neon


